name: CI Pipeline

# This workflow is triggered on pushes and pull requests
on:
  push:
  pull_request:
    branches:
      - dev

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        script :
          - echo "Ceci est un test de modification du fichier ci.yml"


